version: 2.1
commands:
  deployment_setup:
    steps:
      - run:
          name: "Set the Tier"
          command: |
            TIER=DEV
            if [[ ${CIRCLE_BRANCH} =~ isb-cgc-(prod|uat|test).* ]]; then
              TIER=$(awk -F- '{print toupper($3)}' \<<< ${CIRCLE_BRANCH})
            fi
            echo "export TIER=${TIER}" >> $BASH_ENV
            echo "Tier was identified as ${TIER} for branch ${CIRCLE_BRANCH}"
      - run:
          name: "Assign Project-level vars"
          command: |
            KEY=${DEPLOYMENT_KEY_ISB_CGC}
            CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CGC}
            PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CGC}
            if [[ ${TIER} == "PROD" ]] || [[ ${TIER} == "DEV" ]]; then
              echo "Using default project ${PROJECT_ID} and related deployment SA."
            elif [[ ${TIER} == "UAT" ]]; then
              KEY=${DEPLOYMENT_KEY_ISB_CGC_UAT}
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CGC_UAT}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CGC_UAT}
            elif [[ ${TIER} == "TEST" ]]; then
              KEY=${DEPLOYMENT_KEY_ISB_CGC_TEST}
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CGC_TEST}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CGC_TEST}
            else
              echo "[ERROR] - Unrecognized tier: ${TIER} - exitng."
              exit 1
            fi

            echo "export DEPLOYMENT_KEY=\"${KEY}\"" >> $BASH_ENV
            echo "export DEPLOYMENT_CLIENT_EMAIL=${CLIENT_EMAIL}" >> $BASH_ENV
            echo "export DEPLOYMENT_PROJECT_ID=${PROJECT_ID}" >> $BASH_ENV
  deployment_config:
    steps:
      - run:
          name: "Set tier-specific configuration file"
          command: |
            CONFIG=${DEPLOYMENT_CONFIG_DEV}
            if [[ ${TIER} == "PROD" ]]; then
              echo "Deployment configuration set for production."
              CONFIG=${DEPLOYMENT_CONFIG_PROD}
            elif [[ ${TIER} == "UAT" ]]; then
              echo "Deployment configuration set for UAT."
              CONFIG=${DEPLOYMENT_CONFIG_UAT}
            elif [[ ${TIER} == "TEST" ]]; then
              echo "Deployment configuration set for test."
              CONFIG=${DEPLOYMENT_CONFIG_TEST}
            elif [[ ${TIER} == "DEV" ]]; then
              echo "Deployment configuration set for mvm/dev."
            else
              echo "[ERROR] - Unrecognized tier: ${TIER}"
              CONFIG=
            fi

            if [[ -n $CONFIG ]]; then
              echo ${CONFIG} | base64 --decode --ignore-garbage > config_file.txt
              <config_file.txt | xargs -I{} echo export {} >> $BASH_ENV
              echo "Testing vars: env file is ${ENV_FILE}"
            else
              echo "[ERROR] Couldn't assign deployment configuration file - exiting."
              exit 1
            fi

jobs:
  build_job:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    working_directory: ~/ISB-CGC-Webapp
    docker:
      - image: circleci/python:3.7.0
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_USER: ubuntu
          MYSQL_PASSWORD: "isb"
          MYSQL_ROOT_PASSWORD: "isb"
    steps:
      - checkout
      - run:
          name: Set Python Path
          command: |
            echo "export PYTHONPATH=/home/circleci/${CIRCLE_PROJECT_REPONAME}:/home/circleci/${CIRCLE_PROJECT_REPONAME}/lib:/usr/lib/google-cloud-sdk/platform/google_appengine" >> $BASH_ENV
      - restore_cache:
          keys:
            - isb-cgc-webapp-lib-{{ checksum "requirements.txt" }}
      - restore_cache:
          keys:
            - isb-cgc-webapp-google-deps-{{ checksum "shell/install-deps.sh" }}
      - run:
          name: Install Dependencies
          command: |
            sudo -E /bin/bash ./shell/install-deps.sh
      - save_cache:
          key: isb-cgc-webapp-lib-{{ checksum "requirements.txt" }}
          paths:
            - ./lib
      - deployment_setup
      - run:
          name: Auth
          command: |
            sudo -E /bin/sh ./shell/gcloud_authenticate.sh
      - deployment_config
      - run:
          name: Staging and Database testing
          command: |
            sudo -E /bin/bash ./shell/gcloud-pull-staging-files.sh
            sudo -E /bin/bash ./shell/database-setup.sh
      - save_cache:
          key: isb-cgc-webapp-{{ epoch }}
          paths:
            - ./adminrestrict
            - ./.git
            - ./demo
            - ./genes
            - ./seqpeek
            - ./shell
            - ./tasks
            - ./variables
            - ./notebooks
            - ./workbooks
            - ./analysis
            - ./bq_data_access
            - ./etc
            - ./static
            - ./GenespotRE
            - ./offline
            - ./scripts
            - ./session_security
            - ./templates
            - ./visualizations
            - ./ISB-CGC-Common
            - ./Dockerfile
            - ./main.py
            - ./appengine_config.py
            - ./.dockerignore
            - ./app.yaml
            - ./gunicorn.conf.py
            - ./manage.py
            - ./txt
            - ./json
            - ./.env

  deploy_job:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    working_directory: ~/ISB-CGC-Webapp
    docker:
      - image: circleci/python:3.5.6
    steps:
      - restore_cache:
          keys:
            - isb-cgc-webapp-
      - run:
          name: Install CloudSDK
          command: |
            echo "export CLOUDSDK_CORE_DISABLE_PROMPTS=1" >> $BASH_ENV
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update && sudo apt-get -y --allow-downgrades install google-cloud-sdk=251.0.0-0
      - deployment_setup
      - run:
          name: Auth
          command: |
            sudo -E /bin/sh ./shell/gcloud_authenticate.sh
      - deployment_config
      - deploy:
          command: |
            sudo -E rm -rf ./lib
            sudo -E /bin/bash ./shell/unpack_for_deployment.sh
            sudo -E gcloud app deploy --verbosity=debug ./app.yaml --quiet
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_job
      - deploy_job:
          requires:
            - build_job
          filters:
            branches:
              only:
                - master
                - isb-cgc-test
                - isb-cgc-uat
                - isb-cgc-prod
